<script>
	import { onMount } from 'svelte';
	import { currentTheme } from '../stores/theme.js';

	let codeLines = [
		{ number: 1, content: '# Omarchy Theme Configuration', type: 'comment' },
		{ number: 2, content: '# Generated by Omarchy Theme Builder', type: 'comment' },
		{ number: 3, content: '', type: 'empty' },
		{ number: 4, content: '[colors]', type: 'section' },
		{ number: 5, content: 'background = "#191724"', type: 'property' },
		{ number: 6, content: 'foreground = "#e0def4"', type: 'property' },
		{ number: 7, content: 'surface = "#1f1d2e"', type: 'property' },
		{ number: 8, content: 'accent = "#c4a7e7"', type: 'property' },
		{ number: 9, content: 'muted = "#6e6a86"', type: 'property' },
		{ number: 10, content: '', type: 'empty' },
		{ number: 11, content: '[window]', type: 'section' },
		{ number: 12, content: 'border_radius = 8', type: 'property' },
		{ number: 13, content: 'border_width = 2', type: 'property' },
		{ number: 14, content: 'opacity = 0.95', type: 'property' },
		{ number: 15, content: '', type: 'empty' },
		{ number: 16, content: '[icons]', type: 'section' },
		{ number: 17, content: 'theme = "Papirus-Dark"', type: 'property' },
		{ number: 18, content: 'size = 24', type: 'property' },
		{ number: 19, content: '', type: 'empty' },
		{ number: 20, content: '[wallpaper]', type: 'section' },
		{ number: 21, content: 'path = "rose-pine-mountains.jpg"', type: 'property' },
		{ number: 22, content: 'mode = "stretch"', type: 'property' },
		{ number: 23, content: '', type: 'empty' },
		{ number: 24, content: '# Auto-generated on: 2025-01-15 14:32:15', type: 'comment' }
	];

	let activeLineNumber = 5; // Simulate cursor on background color line
	let isTyping = false;
	let currentTyping = '';

	function getLineClass(type) {
		switch (type) {
			case 'comment':
				return 'text-gray-500';
			case 'section':
				return 'text-purple-400 font-semibold';
			case 'property':
				return 'text-blue-400';
			case 'empty':
				return '';
			default:
				return 'text-gray-300';
		}
	}

	function formatPropertyLine(content) {
		if (!content.includes('=')) return content;

		const [key, ...valueParts] = content.split('=');
		const value = valueParts.join('=').trim();

		return {
			key: key.trim(),
			value: value
		};
	}

	function simulateTyping() {
		const typingTexts = [
			'# This theme adapts in real-time...',
			'accent = "#eb6f92"  # Changed to love color',
			'background = "#1a1b26"  # Tokyo Night style',
			'# Perfect for coding sessions!'
		];

		let textIndex = 0;

		const typeNextText = () => {
			if (textIndex >= typingTexts.length) {
				textIndex = 0;
			}

			const text = typingTexts[textIndex];
			isTyping = true;
			currentTyping = '';

			let charIndex = 0;
			const typeChar = () => {
				if (charIndex < text.length) {
					currentTyping = text.substring(0, charIndex + 1);
					charIndex++;
					setTimeout(typeChar, 80 + Math.random() * 40);
				} else {
					setTimeout(() => {
						isTyping = false;
						currentTyping = '';
						textIndex++;
						setTimeout(typeNextText, 3000);
					}, 2000);
				}
			};

			setTimeout(typeChar, 1000);
		};

		setTimeout(typeNextText, 2000);
	}

	onMount(() => {
		simulateTyping();

		// Simulate cursor movement
		const cursorInterval = setInterval(() => {
			activeLineNumber = Math.floor(Math.random() * 10) + 5; // Random line between 5-15
		}, 4000);

		return () => {
			clearInterval(cursorInterval);
		};
	});

	// Update code content when theme changes
	$: if ($currentTheme) {
		// Update color values in the code to match current theme
		codeLines = codeLines.map(line => {
			if (line.content.includes('background =')) {
				return { ...line, content: `background = "${$currentTheme.colors.background}"` };
			} else if (line.content.includes('foreground =')) {
				return { ...line, content: `foreground = "${$currentTheme.colors.foreground}"` };
			} else if (line.content.includes('surface =')) {
				return { ...line, content: `surface = "${$currentTheme.colors.surface}"` };
			} else if (line.content.includes('accent =')) {
				return { ...line, content: `accent = "${$currentTheme.colors.iris}"` };
			} else if (line.content.includes('muted =')) {
				return { ...line, content: `muted = "${$currentTheme.colors.muted}"` };
			} else if (line.content.includes('theme =') && line.content.includes('"')) {
				return { ...line, content: `theme = "${$currentTheme.iconTheme}"` };
			}
			return line;
		});
	}
</script>

<div
	class="code-editor-container h-full bg-gray-900 text-sm overflow-hidden"
	style="background: var(--omarchy-surface); color: var(--omarchy-fg);"
>
	<!-- Editor Header -->
	<div
		class="editor-header flex items-center justify-between px-4 py-2 bg-gray-800 border-b border-gray-700"
		style="background: var(--omarchy-highlight-med); border-color: var(--omarchy-overlay);"
	>
		<div class="flex items-center space-x-4">
			<!-- File tabs -->
			<div class="flex space-x-1">
				<div
					class="tab active-tab px-3 py-1 bg-gray-700 rounded-t text-xs font-medium"
					style="background: var(--omarchy-surface); color: var(--omarchy-fg); border-bottom: 2px solid var(--omarchy-iris);"
				>
					theme.conf
				</div>
				<div
					class="tab px-3 py-1 rounded-t text-xs text-gray-400 hover:bg-gray-600"
					style="color: var(--omarchy-muted);"
				>
					colors.conf
				</div>
				<div
					class="tab px-3 py-1 rounded-t text-xs text-gray-400 hover:bg-gray-600"
					style="color: var(--omarchy-muted);"
				>
					waybar.css
				</div>
			</div>
		</div>

		<!-- Editor controls -->
		<div class="flex items-center space-x-2 text-xs text-gray-400" style="color: var(--omarchy-muted);">
			<span>UTF-8</span>
			<span>•</span>
			<span>Ln 5, Col 12</span>
			<span>•</span>
			<span>CONF</span>
		</div>
	</div>

	<!-- Editor Content -->
	<div class="editor-content flex h-full">
		<!-- Line Numbers -->
		<div
			class="line-numbers bg-gray-800 px-3 py-4 text-right text-gray-500 select-none font-mono border-r border-gray-700"
			style="background: var(--omarchy-highlight-low); color: var(--omarchy-muted); border-color: var(--omarchy-overlay); min-width: 3rem;"
		>
			{#each codeLines as line}
				<div
					class="line-number leading-6"
					class:active-line={line.number === activeLineNumber}
					style="color: {line.number === activeLineNumber ? 'var(--omarchy-iris)' : 'var(--omarchy-muted)'};"
				>
					{line.number}
				</div>
			{/each}
			{#if isTyping}
				<div
					class="line-number leading-6"
					style="color: var(--omarchy-iris);"
				>
					{codeLines.length + 1}
				</div>
			{/if}
		</div>

		<!-- Code Content -->
		<div class="code-content flex-1 p-4 font-mono leading-6 overflow-y-auto">
			{#each codeLines as line}
				<div
					class="code-line leading-6 relative"
					class:active-line={line.number === activeLineNumber}
				>
					{#if line.type === 'comment'}
						<span class="text-gray-500" style="color: var(--omarchy-muted); font-style: italic;">
							{line.content}
						</span>
					{:else if line.type === 'section'}
						<span class="text-purple-400 font-semibold" style="color: var(--omarchy-iris);">
							{line.content}
						</span>
					{:else if line.type === 'property'}
						{@const formatted = formatPropertyLine(line.content)}
						<span class="text-blue-400" style="color: var(--omarchy-pine);">{formatted.key}</span>
						<span class="text-gray-300" style="color: var(--omarchy-subtle);"> = </span>
						<span class="text-orange-400" style="color: var(--omarchy-gold);">{formatted.value}</span>
					{:else if line.type === 'empty'}
						<span>&nbsp;</span>
					{:else}
						<span class="text-gray-300" style="color: var(--omarchy-fg);">
							{line.content}
						</span>
					{/if}

					<!-- Cursor indicator -->
					{#if line.number === activeLineNumber}
						<span
							class="cursor-indicator absolute right-0 w-2 h-6 bg-purple-400 opacity-60 animate-pulse"
							style="background: var(--omarchy-iris);"
						></span>
					{/if}
				</div>
			{/each}

			<!-- Typing simulation -->
			{#if isTyping && currentTyping}
				<div class="code-line leading-6 relative">
					<span class="text-gray-500" style="color: var(--omarchy-muted); font-style: italic;">
						{currentTyping}
					</span>
					<span
						class="cursor-blink text-white ml-1 animate-pulse"
						style="color: var(--omarchy-fg);"
					>
						|
					</span>
				</div>
			{/if}
		</div>
	</div>

	<!-- Status Bar -->
	<div
		class="editor-status-bar flex items-center justify-between px-4 py-1 bg-gray-800 border-t border-gray-700 text-xs"
		style="background: var(--omarchy-highlight-med); border-color: var(--omarchy-overlay); color: var(--omarchy-muted);"
	>
		<div class="flex items-center space-x-4">
			<div class="flex items-center space-x-1">
				<div class="w-2 h-2 bg-green-400 rounded-full" style="background: var(--omarchy-foam);"></div>
				<span>Saved</span>
			</div>
			<span>•</span>
			<span>Theme Builder Connected</span>
		</div>

		<div class="flex items-center space-x-4">
			<span>Spaces: 2</span>
			<span>•</span>
			<span>CONF</span>
			<span>•</span>
			<span>Live Preview: ON</span>
		</div>
	</div>
</div>

<style>
	.code-editor-container {
		font-family: 'JetBrains Mono', 'Fira Code', Monaco, Consolas, monospace;
	}

	.tab {
		transition: all 0.2s ease;
		cursor: pointer;
	}

	.tab:hover {
		background: var(--omarchy-highlight-med);
	}

	.active-line {
		background: var(--omarchy-highlight-low);
	}

	.code-content::-webkit-scrollbar {
		width: 6px;
	}

	.code-content::-webkit-scrollbar-track {
		background: var(--omarchy-surface);
	}

	.code-content::-webkit-scrollbar-thumb {
		background: var(--omarchy-muted);
		border-radius: 3px;
	}

	.code-content::-webkit-scrollbar-thumb:hover {
		background: var(--omarchy-accent);
	}

	.cursor-indicator {
		animation: pulse 1.5s ease-in-out infinite;
	}

	.cursor-blink {
		animation: blink 1s ease-in-out infinite;
	}

	@keyframes blink {
		0%, 50% { opacity: 1; }
		51%, 100% { opacity: 0; }
	}

	@media (max-width: 768px) {
		.code-editor-container {
			font-size: 0.75rem;
		}

		.line-numbers {
			min-width: 2.5rem;
		}
	}
</style>
