<script>
	import { onMount } from 'svelte';
	import { currentTheme } from '../stores/theme.js';

	let terminalLines = [];
	let currentLine = '';
	let isTyping = false;
	let terminalRef;
	let cursor = '█';
	let cursorVisible = true;

	const mockCommands = [
		{ command: 'neofetch', output: ['','                   -`                    user@omarchy', '                  .o+`                   --------------', '                 `ooo/                   OS: Arch Linux x86_64', '                `+oooo:                   Host: Omarchy Desktop', '               `+oooooo:                  Kernel: 6.1.0-omarchy', '               -+oooooo+:                 Uptime: 2 hours, 42 mins', '             `/:-:++oooo+:                Packages: 1847 (pacman)', '            `/++++/+++++++:               Shell: zsh 5.9', '           `/++++++++++++++:              Resolution: 2560x1440', '          `/+++ooooooooo+++/             DE: Hyprland', '         ./ooosssso++osssso+`            WM: Hyprland', '        .oossssso-````/ossso+`           WM Theme: Rose Pine', '       -osssssso.      :ssssso.          Theme: Rose Pine [GTK3]', '      :osssssss/        osssso+-         Icons: Papirus-Dark', '     /ossssssss/        +ssssooo:        Terminal: Alacritty', '   `/ossssso+/:-        -:/+osssso+-     CPU: AMD Ryzen 7 5800X (16) @ 3.8GHz', '  `+sso+:-`                 `.-/+oso:    GPU: NVIDIA GeForce RTX 3080', ' `++:.                           `-/+/    Memory: 6420MiB / 32768MiB', ' .`                                 `/    ',''] },
		{ command: 'ls -la ~/.config/omarchy/themes/', output: ['total 24', 'drwxr-xr-x 6 user user 4096 Jan 15 14:32 .', 'drwxr-xr-x 3 user user 4096 Jan 15 14:30 ..', 'drwxr-xr-x 2 user user 4096 Jan 15 14:32 catppuccin', 'drwxr-xr-x 2 user user 4096 Jan 15 14:31 nord', 'drwxr-xr-x 2 user user 4096 Jan 15 14:32 rose-pine', 'drwxr-xr-x 2 user user 4096 Jan 15 14:30 tokyo-night'] },
		{ command: 'cat ~/.config/omarchy/current-theme.conf', output: ['# Omarchy Theme Configuration', '# Generated by Omarchy Theme Builder', '', 'THEME_NAME="Rose Pine"', 'PRIMARY_BACKGROUND="#191724"', 'PRIMARY_FOREGROUND="#e0def4"', 'ACCENT_COLOR="#c4a7e7"', 'SURFACE_COLOR="#1f1d2e"', 'OVERLAY_COLOR="#26233a"', 'MUTED_COLOR="#6e6a86"', '', 'ICON_THEME="Papirus-Dark"', 'WALLPAPER="rose-pine-mountains.jpg"', 'LIGHT_MODE=false'] },
		{ command: 'htop', output: ['Press q to quit...', '  1  [████████████████████████████████████████████████████████████████ 89.2%]', '  2  [██████████████████████████████████████████                       67.4%]', '  3  [███████████████████████████████████████████████████              78.9%]', '  4  [████████████████████████████████████████████████████████         82.1%]', '  5  [██████████████████████████████████████████████████████████████   91.5%]', '  6  [███████████████████████████████████████████████████████          81.2%]', '  7  [██████████████████████████████████████████████                   69.8%]', '  8  [████████████████████████████████████████████████████████████     87.3%]', '', '  Mem[██████████████████████████████████████████                   6.42G/32.0G]', '  Swp[                                                             0K/8.00G]', '', '  PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command', ' 1847 user       20   0 2.31G  247M  89.2M R 89.2  0.8  0:03.42 Hyprland', ' 2156 user       20   0  451M  67.4M  34.2M S 12.4  0.2  0:01.23 alacritty', ' 2234 user       20   0  1.2G  156M  78.9M S  8.7  0.5  0:02.45 code'] },
		{ command: 'omarchy-theme apply rose-pine', output: ['🎨 Applying Rose Pine theme...', '✓ Updated Hyprland configuration', '✓ Updated Waybar styles', '✓ Updated Alacritty colors', '✓ Updated Mako notification daemon', '✓ Updated GTK theme', '✓ Applied icon theme: Papirus-Dark', '✓ Set wallpaper: rose-pine-mountains.jpg', '', '🎉 Rose Pine theme applied successfully!', '🔄 Restart required for some applications'] }
	];

	let commandIndex = 0;
	let outputIndex = 0;
	let charIndex = 0;

	function typeText(text, callback) {
		if (!text) {
			callback();
			return;
		}

		isTyping = true;
		let i = 0;
		const interval = setInterval(() => {
			if (i < text.length) {
				currentLine = text.substring(0, i + 1);
				i++;
			} else {
				clearInterval(interval);
				isTyping = false;
				callback();
			}
		}, 50 + Math.random() * 30); // Slight variation in typing speed
	}

	function addPrompt() {
		return `[user@omarchy ~]$ `;
	}

	function simulateCommand() {
		if (commandIndex >= mockCommands.length) {
			// Reset and start over
			setTimeout(() => {
				commandIndex = 0;
				outputIndex = 0;
				terminalLines = [];
				simulateCommand();
			}, 5000);
			return;
		}

		const cmd = mockCommands[commandIndex];
		const prompt = addPrompt();

		// Type the command
		typeText(prompt + cmd.command, () => {
			// Add the command line to history
			terminalLines = [...terminalLines, currentLine];
			currentLine = '';

			// Add output lines one by one
			let lineIndex = 0;
			const addOutputLine = () => {
				if (lineIndex < cmd.output.length) {
					terminalLines = [...terminalLines, cmd.output[lineIndex]];
					lineIndex++;
					setTimeout(addOutputLine, 100 + Math.random() * 200);
				} else {
					// Move to next command
					commandIndex++;
					setTimeout(simulateCommand, 2000 + Math.random() * 1000);
				}
			};

			setTimeout(addOutputLine, 500);
		});
	}

	function scrollToBottom() {
		if (terminalRef) {
			terminalRef.scrollTop = terminalRef.scrollHeight;
		}
	}

	onMount(() => {
		// Start cursor blinking
		const cursorInterval = setInterval(() => {
			cursorVisible = !cursorVisible;
		}, 530);

		// Start the terminal simulation
		setTimeout(simulateCommand, 1000);

		return () => {
			clearInterval(cursorInterval);
		};
	});

	$: if (terminalLines.length > 0) {
		setTimeout(scrollToBottom, 10);
	}
</script>

<div
	class="terminal-container h-full bg-gray-900 font-mono text-sm overflow-hidden"
	style="background: var(--omarchy-surface); color: var(--omarchy-fg);"
>
	<!-- Terminal Content -->
	<div
		bind:this={terminalRef}
		class="terminal-content h-full p-4 overflow-y-auto"
	>
		<!-- Terminal Header Info -->
		<div class="mb-4 text-xs opacity-60" style="color: var(--omarchy-muted);">
			<div>Terminal - Omarchy Theme Builder Demo</div>
			<div>Connected to: user@omarchy</div>
			<div class="mt-2 border-b border-gray-700 pb-2" style="border-color: var(--omarchy-overlay);"></div>
		</div>

		<!-- Terminal History -->
		{#each terminalLines as line, index (index)}
			<div class="terminal-line leading-relaxed">
				{#if line.startsWith('[user@omarchy')}
					<!-- Command line -->
					<span class="text-green-400" style="color: var(--omarchy-foam);">{line.split(']$ ')[0]}]$</span>
					{#if line.split(']$ ')[1]}
						<span class="text-white ml-1" style="color: var(--omarchy-fg);">{line.split(']$ ')[1]}</span>
					{/if}
				{:else if line.includes('✓')}
					<!-- Success messages -->
					<span class="text-green-400" style="color: var(--omarchy-foam);">{line}</span>
				{:else if line.includes('🎨') || line.includes('🎉') || line.includes('🔄')}
					<!-- Emoji messages -->
					<span class="text-purple-400" style="color: var(--omarchy-iris);">{line}</span>
				{:else if line.includes('ERROR') || line.includes('error')}
					<!-- Error messages -->
					<span class="text-red-400" style="color: var(--omarchy-love);">{line}</span>
				{:else if line.includes('WARNING') || line.includes('warning')}
					<!-- Warning messages -->
					<span class="text-yellow-400" style="color: var(--omarchy-gold);">{line}</span>
				{:else if line.startsWith('#')}
					<!-- Comments -->
					<span class="text-gray-500" style="color: var(--omarchy-muted);">{line}</span>
				{:else if line.includes('=') && (line.includes('"') || line.includes("'"))}
					<!-- Config values -->
					<span class="text-blue-400" style="color: var(--omarchy-pine);">{line.split('=')[0]}=</span><span class="text-orange-400" style="color: var(--omarchy-gold);">{line.split('=').slice(1).join('=')}</span>
				{:else if line.match(/^\s*\d+\s+/)}
					<!-- Process list lines -->
					<span class="text-cyan-400" style="color: var(--omarchy-foam);">{line}</span>
				{:else if line.includes('drwxr-xr-x') || line.includes('-rw-r--r--')}
					<!-- File listing -->
					<span class="text-blue-400" style="color: var(--omarchy-pine);">{line}</span>
				{:else}
					<!-- Regular output -->
					<span class="text-gray-300" style="color: var(--omarchy-fg);">{line}</span>
				{/if}
			</div>
		{/each}

		<!-- Current typing line -->
		{#if currentLine}
			<div class="terminal-line leading-relaxed">
				{#if currentLine.startsWith('[user@omarchy')}
					<span class="text-green-400" style="color: var(--omarchy-foam);">{currentLine.split(']$ ')[0]}]$</span>
					{#if currentLine.split(']$ ')[1]}
						<span class="text-white ml-1" style="color: var(--omarchy-fg);">{currentLine.split(']$ ')[1]}</span>
					{/if}
				{:else}
					<span class="text-gray-300" style="color: var(--omarchy-fg);">{currentLine}</span>
				{/if}
				{#if isTyping && cursorVisible}
					<span class="cursor text-white" style="color: var(--omarchy-fg);">{cursor}</span>
				{/if}
			</div>
		{/if}

		<!-- Cursor for empty prompt -->
		{#if !currentLine && !isTyping}
			<div class="terminal-line leading-relaxed">
				<span class="text-green-400" style="color: var(--omarchy-foam);">[user@omarchy ~]$</span>
				{#if cursorVisible}
					<span class="cursor text-white ml-1" style="color: var(--omarchy-fg);">{cursor}</span>
				{/if}
			</div>
		{/if}
	</div>
</div>

<style>
	.terminal-container {
		font-family: 'JetBrains Mono', 'Fira Code', Monaco, Consolas, monospace;
		font-size: 0.875rem;
		line-height: 1.5;
	}

	.terminal-content::-webkit-scrollbar {
		width: 6px;
	}

	.terminal-content::-webkit-scrollbar-track {
		background: var(--omarchy-surface);
	}

	.terminal-content::-webkit-scrollbar-thumb {
		background: var(--omarchy-muted);
		border-radius: 3px;
	}

	.terminal-content::-webkit-scrollbar-thumb:hover {
		background: var(--omarchy-accent);
	}

	.terminal-line {
		white-space: pre-wrap;
		word-break: break-all;
		margin-bottom: 2px;
	}

	.cursor {
		animation: none;
	}

	@media (max-width: 768px) {
		.terminal-container {
			font-size: 0.75rem;
		}
	}
</style>
